# Generated by Django 4.1.5 on 2023-01-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_profile_user_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='src.profile'),
        ),
    ]
