# Generated by Django 4.1.5 on 2023-01-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_profile_user_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_study_guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='src.study_guide'),
        ),
    ]
