# Generated by Django 4.1.5 on 2023-01-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_question_question_study_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_study_guide',
            new_name='from_study_guide',
        ),
    ]
